services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    command: >
      redis-server --port 7001
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7001
                   --cluster-announce-bus-port 17001
    ports:
      - "7001:7001"
      - "17001:17001"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.11

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    command: >
      redis-server --port 7002
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7002
                   --cluster-announce-bus-port 17002
    ports:
      - "7002:7002"
      - "17002:17002"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.12

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    command: >
      redis-server --port 7003
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7003
                   --cluster-announce-bus-port 17003
    ports:
      - "7003:7003"
      - "17003:17003"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.13

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    command: >
      redis-server --port 7004
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7004
                   --cluster-announce-bus-port 17004
    ports:
      - "7004:7004"
      - "17004:17004"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.14

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    command: >
      redis-server --port 7005
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7005
                   --cluster-announce-bus-port 17005
    ports:
      - "7005:7005"
      - "17005:17005"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.15

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    command: >
      redis-server --port 7006
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --bind 0.0.0.0
                   --cluster-announce-ip 192.168.2.30
                   --cluster-announce-port 7006
                   --cluster-announce-bus-port 17006
    ports:
      - "7006:7006"
      - "17006:17006"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.16

  redis-cluster-init:
    image: redis:7.2
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: >
      sh -c "sleep 30 && echo yes | redis-cli --cluster create 192.168.2.30:7001 192.168.2.30:7002 192.168.2.30:7003 192.168.2.30:7004 192.168.2.30:7005 192.168.2.30:7006 --cluster-replicas 1"
    networks:
      redis-cluster:
        ipv4_address: 172.20.0.100

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
